# 기출문제 제9회(2024-11-30 시행)
---

## 작업형 제1유형
---

### 1. 데이터에서 (연도, 성별, 지역코드)별 총 대출액의 합계를 구하시오. 이후, 각 (연도, 지역코드)별로 남성과 여성의 총 대출액 차이의 절댓값을 계산하고, 성별 간 총 대출액 차이가 가장 큰 지역코드를 구하시오. (총 대출액 = 금액1 + 금액2)

In [183]:
import pandas as pd

df1_1 = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_1_1.csv")
df1_1.head()

   year  gender  지역코드    금액1    금액2
0  2018       0   143  70713  43210
1  2019       0   183  40306  39663
2  2017       0   129  26646  41631
3  2019       0   161  56843  12455
4  2019       0   174  26371   9014

In [184]:
df1_1["총 대출액"] = df1_1["금액1"] + df1_1["금액2"]
df1_1.head()

   year  gender  지역코드    금액1    금액2   총 대출액
0  2018       0   143  70713  43210  113923
1  2019       0   183  40306  39663   79969
2  2017       0   129  26646  41631   68277
3  2019       0   161  56843  12455   69298
4  2019       0   174  26371   9014   35385

In [185]:
df1_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    100 non-null    int64
 1   gender  100 non-null    int64
 2   지역코드    100 non-null    int64
 3   금액1     100 non-null    int64
 4   금액2     100 non-null    int64
 5   총 대출액   100 non-null    int64
dtypes: int64(6)
memory usage: 4.8 KB

In [186]:
df_1 = df1_1.groupby(["year", "gender", "지역코드"])["총 대출액"].sum()
df_1

year  gender  지역코드
2015  0       131      37881
              151      32197
              195     161121
              197      93317
      1       101      87088
                       ...
2020  1       102     105908
              168      85313
              172      97854
              192     109436
              195      34792
Name: 총 대출액, Length: 94, dtype: int64

In [187]:
df_2 = df1_1.groupby(["year", "지역코드"])[["총 대출액","gender"]].sum()
df_2

            총 대출액  gender
year 지역코드
2015 101    87088       1
     118   100609       1
     130    41599       1
     131    37881       0
     150    56775       1
...           ...     ...
2020 176    85767       0
     178    71066       0
     192   109436       1
     195    34792       1
     196    76900       0

[91 rows x 2 columns]

In [188]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 91 entries, (np.int64(2015), np.int64(101)) to (np.int64(2020), np.int64(196))
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   총 대출액   91 non-null     int64
 1   gender  91 non-null     int64
dtypes: int64(2)
memory usage: 2.2 KB

```
모르는 것: 연도, 지역코드별 성별간 총 대출액의 차이를 구하라 되어있는데, 연도, 지역코드가 동일한 데이터가 없는 것 같다. 이부분을 어떻게 해결해야할지 모르겠다. 
```

### 2. 각 연도별 최대 검거율을 가진 범죄유형을 찾아서 해당 연도 및 유형의 검거건수들의 총합을 구하시오.(검거율 = 검거건수 / 발생건수)

In [189]:
import pandas as pd

df1_2 = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_1_2.csv")
df1_2.head()

,연도,구분,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10
0,2000,발생건수,302,635,470,306,271,900,220,814,321,666
1,2000,검거건수,302,430,470,187,271,199,220,230,321,408
2,2001,발생건수,969,543,691,613,585,391,476,360,659,513
3,2001,검거건수,121,352,691,613,574,158,476,360,575,513
4,2002,발생건수,982,389,886,762,766,443,704,330,684,846

In [190]:
df1_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   연도      50 non-null     int64
 1   구분      50 non-null     object
 2   범죄유형1   50 non-null     int64
 3   범죄유형2   50 non-null     int64
 4   범죄유형3   50 non-null     int64
 5   범죄유형4   50 non-null     int64
 6   범죄유형5   50 non-null     int64
 7   범죄유형6   50 non-null     int64
 8   범죄유형7   50 non-null     int64
 9   범죄유형8   50 non-null     int64
 10  범죄유형9   50 non-null     int64
 11  범죄유형10  50 non-null     int64
dtypes: int64(11), object(1)
memory usage: 4.8+ KB

In [191]:
# 1. 데이터프레임을 연도, 발생건수, 검거 건수, 검거율로 다시 그룹화 해야한다.
df1_2_generation = df1_2[df1_2["구분"] == "발생건수"]
df1_2_generation.head()

,연도,구분,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10
0,2000,발생건수,302,635,470,306,271,900,220,814,321,666
2,2001,발생건수,969,543,691,613,585,391,476,360,659,513
4,2002,발생건수,982,389,886,762,766,443,704,330,684,846
6,2003,발생건수,764,539,291,566,654,627,708,975,234,405
8,2004,발생건수,601,929,755,361,401,469,470,655,661,926

In [192]:
df1_2_arrest = df1_2[df1_2["구분"] == "검거건수"]
df1_2_arrest.head()

,연도,구분,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10
1,2000,검거건수,302,430,470,187,271,199,220,230,321,408
3,2001,검거건수,121,352,691,613,574,158,476,360,575,513
5,2002,검거건수,120,266,373,487,700,415,113,330,684,445
7,2003,검거건수,180,539,291,101,489,627,205,871,234,405
9,2004,검거건수,351,801,395,361,401,469,437,152,661,316

In [193]:
crim_group = ["범죄유형1", "범죄유형2", "범죄유형3", "범죄유형4", "범죄유형5", "범죄유형6", "범죄유형7", "범죄유형8", "범죄유형9", "범죄유형10"]
df1_2_generation["총 발생건수"] = df1_2_generation[crim_group].sum(axis=1)
df1_2_arrest["총 검거건수"] = df1_2_arrest[crim_group].sum(axis=1)
df1_2_generation.head()

C:\Users\hambu\AppData\Local\Temp\ipykernel_28676\787600946.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_2_generation["총 발생건수"] = df1_2_generation[crim_group].sum(axis=1)
C:\Users\hambu\AppData\Local\Temp\ipykernel_28676\787600946.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_2_arrest["총 검거건수"] = df1_2_arrest[crim_group].sum(axis=1)

,연도,구분,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10,총 발생건수
0,2000,발생건수,302,635,470,306,271,900,220,814,321,666,4905
2,2001,발생건수,969,543,691,613,585,391,476,360,659,513,5800
4,2002,발생건수,982,389,886,762,766,443,704,330,684,846,6792
6,2003,발생건수,764,539,291,566,654,627,708,975,234,405,5763
8,2004,발생건수,601,929,755,361,401,469,470,655,661,926,6228

In [194]:
df1_2_arrest.head()

,연도,구분,범죄유형1,범죄유형2,범죄유형3,범죄유형4,범죄유형5,범죄유형6,범죄유형7,범죄유형8,범죄유형9,범죄유형10,총 검거건수
1,2000,검거건수,302,430,470,187,271,199,220,230,321,408,3038
3,2001,검거건수,121,352,691,613,574,158,476,360,575,513,4433
5,2002,검거건수,120,266,373,487,700,415,113,330,684,445,3933
7,2003,검거건수,180,539,291,101,489,627,205,871,234,405,3942
9,2004,검거건수,351,801,395,361,401,469,437,152,661,316,4344

In [195]:
df1_2_final = pd.merge(df1_2_generation[["연도", "총 발생건수"]], df1_2_arrest[["연도", "총 검거건수"]], on="연도")
df1_2_final.head()

     연도  총 발생건수  총 검거건수
0  2000    4905    3038
1  2001    5800    4433
2  2002    6792    3933
3  2003    5763    3942
4  2004    6228    4344

In [196]:
df1_2_final["검거율"] = df1_2_final["총 검거건수"] / df1_2_final["총 발생건수"]
df1_2_final.head()

     연도  총 발생건수  총 검거건수       검거율
0  2000    4905    3038  0.619368
1  2001    5800    4433  0.764310
2  2002    6792    3933  0.579064
3  2003    5763    3942  0.684019
4  2004    6228    4344  0.697495

In [197]:
df1_2_final.sort_values("검거율", ascending=False)
# 1. 검거율이 가장 높은 연도는? 2018년
# 2. 검거율이 가장 높은 연도의 검거건수: 4590건

      연도  총 발생건수  총 검거건수       검거율
13  2013    5506    4590  0.833636
16  2016    4966    3952  0.795812
22  2022    5670    4478  0.789771
23  2023    5380    4162  0.773606
1   2001    5800    4433  0.764310
15  2015    4631    3525  0.761175
21  2021    6470    4787  0.739876
5   2005    4958    3658  0.737797
10  2010    7202    5105  0.708831
14  2014    6765    4739  0.700517
4   2004    6228    4344  0.697495
7   2007    7107    4936  0.694527
3   2003    5763    3942  0.684019
6   2006    5337    3635  0.681094
8   2008    6623    4498  0.679148
12  2012    6811    4444  0.652474
17  2017    6024    3793  0.629648
11  2011    5883    3696  0.628251
9   2009    7319    4538  0.620030
0   2000    4905    3038  0.619368
24  2024    6479    3999  0.617225
2   2002    6792    3933  0.579064
19  2019    5186    2780  0.536059
20  2020    7878    3879  0.492384
18  2018    6806    3306  0.485748

### 3. 제시된 문제를 순서대로풀고, 해답을 제시하시오

**결측치 처리**
1. 평균만족도: 결측치는 평균만족도 컬럼의 전체 평균으로 채우시오.
2. 근속연수: 결측치는 각 부서와 등급별 평균 근속연수로 채우시오. (평균값의 소수점은 버림 처리)

**조건에 따른 평균 계산**

3. A: 부서가 'HR'이고 등급이 'A'인 사람들의 평균 근속연수를 계산하시오.
4. B: 부서가 'Sales'이고 등급이 'B'인 사람들의 평균 교육참가횟수를 계산하시오.
5. A와 B를 더한 값을 구하시오.

In [198]:
import pandas as pd

df1_3 = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_1_3.csv")
df1_3.head()

          부서 등급     평균만족도  근속연수  교육참가횟수
0    Finance  C  4.023911  17.0     8.0
1  Marketing  A  3.756698  14.0    16.0
2         IT  B  2.628697  21.0    13.0
3  Marketing  A  3.196616   NaN    18.0
4  Marketing  C  4.770665  28.0    10.0

In [199]:
df1_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   부서      100 non-null    object
 1   등급      100 non-null    object
 2   평균만족도   90 non-null     float64
 3   근속연수    90 non-null     float64
 4   교육참가횟수  100 non-null    float64
dtypes: float64(3), object(2)
memory usage: 4.0+ KB

In [200]:
df1_3.isnull().sum()

부서         0
등급         0
평균만족도     10
근속연수      10
교육참가횟수     0
dtype: int64

In [201]:
df1_3["평균만족도"] = df1_3["평균만족도"].fillna(df1_3["평균만족도"].mean())
df1_3.isnull().sum()

부서         0
등급         0
평균만족도      0
근속연수      10
교육참가횟수     0
dtype: int64

In [202]:
df1_3.groupby(["부서", "등급"])["근속연수"].mean()

부서         등급
Finance    A     10.200000
           B     18.750000
           C     11.555556
HR         A     17.714286
           B     11.500000
           C     12.000000
IT         A     16.333333
           B     14.800000
           C      8.800000
Marketing  A     19.375000
           B     15.250000
           C     21.833333
Sales      A     17.600000
           B     15.250000
           C     17.363636
Name: 근속연수, dtype: float64

In [203]:
df1_3["근속연수"] = df1_3["근속연수"].fillna(df1_3.groupby(["부서", "등급"])["근속연수"].transform("mean"))     # transform이 무엇인지 모르겠음. 조건 별 평균값으로 대치하는 방법을 모르겠음
df1_3.isnull().sum()

부서        0
등급        0
평균만족도     0
근속연수      0
교육참가횟수    0
dtype: int64

In [204]:
df1_3["근속연수"] = df1_3["근속연수"].astype("int")
df1_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   부서      100 non-null    object
 1   등급      100 non-null    object
 2   평균만족도   100 non-null    float64
 3   근속연수    100 non-null    int64
 4   교육참가횟수  100 non-null    float64
dtypes: float64(2), int64(1), object(2)
memory usage: 4.0+ KB

In [205]:
df1_3.head()

          부서 등급     평균만족도  근속연수  교육참가횟수
0    Finance  C  4.023911    17     8.0
1  Marketing  A  3.756698    14    16.0
2         IT  B  2.628697    21    13.0
3  Marketing  A  3.196616    19    18.0
4  Marketing  C  4.770665    28    10.0

## 작업형 제2유형

제공된 학습용 데이터(9_2_train.csv)는 지역의 특성과 해당 지역의 농업 유형 정보를 포함하고 있다. 학습용 데이터를 활용하여 지역의 농업 유형(라벨)을 예측하는 다중분류 모델을 개발하고, 가장 우수한 모델을 평가용 데이터(9_2_test.csv)에 적용하여 예측 결과를 제출하시오.

※ 모델 성능 지표: Macro F1 Score

※ 타깃(라벨): 농업 유형(0,1,2의 세 가지 클래스)

In [206]:
import pandas as pd

df2_train = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_2_train.csv")
df2_train.head()

     ID  지역 등급   농업면적    연도  라벨
0  2089  부산  B  27406  2010   0
1  1964  대전  C  50520  2006   0
2  1820  울산  B  15030  2021   0
3  1408  부산  A  65007  2019   0
4   205  충남  A  72526  2018   0

In [207]:
df2_test = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_2_test.csv")
df2_test.head()

     ID  지역 등급   농업면적    연도  라벨
0  1094  경남  B   6902  2020   0
1  1341  전북  A  93327  2016   0
2   545  인천  C   1921  2011   1
3   225  대구  C  90240  2010   0
4   690  인천  A  66026  2013   0

In [208]:
df2_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1680 entries, 0 to 1679
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      1680 non-null   int64
 1   지역      1680 non-null   object
 2   등급      1680 non-null   object
 3   농업면적    1680 non-null   int64
 4   연도      1680 non-null   int64
 5   라벨      1680 non-null   int64
dtypes: int64(4), object(2)
memory usage: 78.9+ KB

In [209]:
df2_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      720 non-null    int64
 1   지역      720 non-null    object
 2   등급      720 non-null    object
 3   농업면적    720 non-null    int64
 4   연도      720 non-null    int64
 5   라벨      720 non-null    int64
dtypes: int64(4), object(2)
memory usage: 33.9+ KB

In [210]:
# 지역, 등급에 대한 원-핫 인코딩이 필요해보인다.

df2_train["지역"].value_counts()

지역
서울    134
광주    125
전북    122
전남    121
부산    117
인천    115
경북    115
대전    113
경기    112
울산    111
충북    105
충남    102
경남    101
강원     96
대구     91
Name: count, dtype: int64

In [211]:
df2_train["등급"].value_counts()

등급
A    573
B    555
C    552
Name: count, dtype: int64

불필요 칼럼이 늘어날 듯하여 두 칼럼 모두 매핑을 통해 숫자로 처리할 예정이다.

In [212]:
local_dict = {
    '부산':0, '대전':1, '울산':2, 
    '충남':3, '경남':4, '인천':5, 
    '대구':6, '경기':7, '전북':8, 
    '서울':9, '광주':10,'경북':11, 
    '전남':12, '강원':13, '충북':14
       }
grade_dict = {
    'A':0, 'B':1, 'C':2}

In [213]:
df2_train["지역"] = df2_train["지역"].map(local_dict)
df2_train["등급"] = df2_train["등급"].map(grade_dict)
df2_train.head()

     ID  지역  등급   농업면적    연도  라벨
0  2089   0   1  27406  2010   0
1  1964   1   2  50520  2006   0
2  1820   2   1  15030  2021   0
3  1408   0   0  65007  2019   0
4   205   3   0  72526  2018   0

In [214]:
# test 데이터에도 동일하게 적용해야한다.
df2_test["지역"] = df2_test["지역"].map(local_dict)
df2_test["등급"] = df2_test["등급"].map(grade_dict)

In [215]:
df2_train.describe()

,ID,지역,등급,농업면적,연도,라벨
count,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000,1680.000000
mean,1185.172024,7.033929,0.987500,50240.034524,2012.035119,0.166667
std,694.492307,4.291012,0.818465,29019.924337,7.327566,0.471545
min,0.000000,0.000000,0.000000,113.000000,2000.000000,0.000000
25%,575.750000,3.000000,0.000000,25602.250000,2006.000000,0.000000
50%,1185.500000,7.000000,1.000000,49158.500000,2012.000000,0.000000
75%,1784.250000,11.000000,2.000000,76504.750000,2018.000000,0.000000
max,2399.000000,14.000000,2.000000,99783.000000,2024.000000,2.000000

In [216]:
df2_train["라벨"].value_counts()

라벨
0    1470
1     140
2      70
Name: count, dtype: int64

특정유형(라벨 0)이 절대 다수인 것을 확인했다. 라벨별로 데이터셋을 나눌 필요가 있을 것 같다. 혹은 클래스 가중치를 이용하면 좋을 것 같다.

In [217]:
df2_train_0 = df2_train[df2_train["라벨"] == 0]
df2_train_1 = df2_train[df2_train["라벨"] == 1]
df2_train_2 = df2_train[df2_train["라벨"] == 2]
df2_train_0

        ID  지역  등급   농업면적    연도  라벨
0     2089   0   1  27406  2010   0
1     1964   1   2  50520  2006   0
2     1820   2   1  15030  2021   0
3     1408   0   0  65007  2019   0
4      205   3   0  72526  2018   0
...    ...  ..  ..    ...   ...  ..
1675  2394   9   2  13852  2001   0
1676  1507   8   0  91420  2019   0
1677   663   9   1  64713  2008   0
1678   909  10   0  23990  2003   0
1679   483   4   2  92790  2006   0

[1470 rows x 6 columns]

In [218]:
df2_train_1

        ID  지역  등급   농업면적    연도  라벨
21    1423  12   2   5455  2006   1
23     204   4   1  10809  2013   1
27    1571   6   1  41939  2016   1
46    2076  10   1  30134  2014   1
61     655   8   2  89212  2009   1
...    ...  ..  ..    ...   ...  ..
1625  2398   5   2  56357  2013   1
1651  1351   0   1  60282  2023   1
1654   487  14   1  90064  2000   1
1662  1841   9   0  87593  2017   1
1667  1376  12   1  55162  2002   1

[140 rows x 6 columns]

In [219]:
df2_train_2

        ID  지역  등급   농업면적    연도  라벨
55     592   1   1  95431  2005   2
78    2234   1   2  29794  2000   2
84     365   0   2  91786  2019   2
119    279   9   0  94768  2013   2
124   1879   9   0  59096  2009   2
...    ...  ..  ..    ...   ...  ..
1537   832   8   0   8211  2013   2
1559  1968   9   2  95962  2016   2
1561   101  14   0  95103  2000   2
1564   863   9   2  46647  2004   2
1641  2006   6   0  85960  2003   2

[70 rows x 6 columns]

In [220]:
# 학습, 평가 데이터셋 분할
from sklearn.model_selection import train_test_split

X_0 = df2_train_0.drop("라벨", axis=1)
y_0 = df2_train_0["라벨"]

X_0_train, X_0_test, y_0_train, y_0_test = train_test_split(X_0, y_0, test_size=0.2, random_state=42)

X_1 = df2_train_1.drop("라벨", axis=1)
y_1 = df2_train_1["라벨"]
X_1_train, X_1_test, y_1_train, y_1_test = train_test_split(X_1, y_1, test_size=0.2, random_state=42)

X_2 = df2_train_2.drop("라벨", axis=1)
y_2 = df2_train_2["라벨"]
X_2_train, X_2_test, y_2_train, y_2_test = train_test_split(X_2, y_2, test_size=0.2, random_state=42)

X_train = pd.concat([X_0_train, X_1_train, X_2_train], axis=0)
y_train = pd.concat([y_0_train, y_1_train, y_2_train], axis=0)
X_test = pd.concat([X_0_test, X_1_test, X_2_test], axis=0)
y_test = pd.concat([y_0_test, y_1_test, y_2_test], axis=0)

In [221]:
# 모델 선언(랜덤 포레스트)
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state=42)
# 모델 학습
model.fit(X_train, y_train)

# 모델 평가(F1 score)
from sklearn.metrics import f1_score
y_pred = model.predict(X_test)
f1 = f1_score(y_test, y_pred, average="weighted")
print("F1 Score:", f1)

F1 Score: 0.8136942675159237

In [222]:
# 모델 예측
X_pred = df2_test.drop("라벨", axis=1)

y_test_pred = model.predict(X_pred)

# 예측결과 저장
submission = pd.DataFrame({
    "ID": df2_test["ID"],
    "라벨": y_test_pred
})

submission.to_csv("./result/result_9th.csv", index=False)

## 작업형 제3유형

### 1. 한 제조 회사에서 생산성을 높이고자 직원들의 주요 생산성 요인을 분석하기로 결정하였다. 이를 위해 200명의 직원 데이터를 수집했으며, 직원들의 근무 기간, 특성 정보, 그리고 개인적인 속성을 조사하였다.

1. design을 예측하는 다중회귀 분석을 시행한 후 유의하지 않은 설명변수 개수를 구하시오(단, 불필요한 칼럼은 제외하며, 모델의 절편향은 포함)
2. 훈련 데이터(학습용 데이터)의 예측값과 실제값의 피어슨 상관계수를 구하시오(소수점 셋째 자리에서 반올림)
3. 적합한 모델을 활용하여 테스트 데이터에서의 RMSE를 구하시오.

In [223]:
import pandas as pd

df3_1 = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_3_1.csv")
df3_1.head()

   id  tenure         f2  f3         f4         f5     design
0   1       7  58.875116   1  58.929804   8.629778  41.297902
1   2      20  56.054831   0  72.885964  13.040569  47.769777
2   3      15  42.797020   1  75.951039  18.546462  50.628621
3   4      11  47.300662   0  38.407204  14.124501  24.725309
4   5       8  48.565378   1  24.867398  18.861890  27.777825

In [224]:
df3_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      200 non-null    int64
 1   tenure  200 non-null    int64
 2   f2      200 non-null    float64
 3   f3      200 non-null    int64
 4   f4      200 non-null    float64
 5   f5      200 non-null    float64
 6   design  200 non-null    float64
dtypes: float64(4), int64(3)
memory usage: 11.1 KB

In [225]:
df3_1.describe()

,id,tenure,f2,f3,f4,f5,design
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,100.500000,9.860000,50.433541,0.465000,51.651509,10.335193,38.610937
std,57.879185,5.815453,10.029043,0.500025,27.970827,5.466430,12.466697
min,1.000000,1.000000,26.819318,0.000000,1.256907,-7.841026,4.967350
25%,50.750000,5.000000,43.631208,0.000000,28.048480,6.863312,28.297675
50%,100.500000,9.000000,49.870681,0.000000,53.983429,10.493881,38.854937
75%,150.250000,15.000000,56.094827,1.000000,75.233928,14.078227,48.445142
max,200.000000,20.000000,82.539851,1.000000,99.728298,25.872211,64.500229

In [226]:
# 시험 조건에 따라 데이터셋을 분할
df3_1_train = df3_1.iloc[:140, :]
df3_1_test = df3_1.iloc[140:, :]

In [227]:
df3_1_train.shape

(140, 7)

In [228]:
df3_1_train.tail()

      id  tenure         f2  f3         f4         f5     design
135  136      13  54.138748   0   9.700875   6.420121  19.456445
136  137       6  55.677684   0  80.780624  13.444191  51.036812
137  138      12  51.481817   0   6.509695  12.333913  18.752659
138  139      12  61.724358   0  84.389089  16.836851  56.074771
139  140      20  55.314000   1   6.111912  14.791269  25.414193

In [229]:
# 독립 변수와 종속 변수 설정
X_train = df3_1_train.drop("design", axis=1)
y_train = df3_1_train["design"]

In [230]:
# 모델 회귀식 계수 유의성 검정(몰랐음)
import statsmodels.api as sm
X_train_sm = sm.add_constant(X_train)  # 상수항 추가
model_sm = sm.OLS(y_train, X_train_sm).fit()
print(model_sm.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                 design   R-squared:                       0.839
Model:                            OLS   Adj. R-squared:                  0.831
Method:                 Least Squares   F-statistic:                     115.1
Date:                Sun, 17 May 2026   Prob (F-statistic):           3.52e-50
Time:                        16:50:21   Log-Likelihood:                -420.65
No. Observations:                 140   AIC:                             855.3
Df Residuals:                     133   BIC:                             875.9
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.4506      2.731      0.531      0.596      -3.951       6.852
id             0.0128      0.011      1.214      0.227      -0.008       0.034
tenure         0.5461      0.077      7.060      0.000       0.393       0.699
f2             0.2094      0.043      4.836      0.000       0.124       0.295
f3            -0.5537      0.854     -0.649      0.518      -2.242       1.135
f4             0.3948      0.016     25.005      0.000       0.364       0.426
f5             0.0172      0.073      0.236      0.814      -0.127       0.162
==============================================================================
Omnibus:                        5.384   Durbin-Watson:                   2.018
Prob(Omnibus):                  0.068   Jarque-Bera (JB):                5.095
Skew:                          -0.464   Prob(JB):                       0.0783
Kurtosis:                       3.119   Cond. No.                         682.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

모델에서 유의하지 않은 설명변수는 [id, f3, f5] 총 3개이다.

In [236]:
# 유의하지 않은 변수 제거 후 모델 재적합
X_train_reduced = X_train.drop(["id", "f3", "f5"], axis=1) 

# 모델 선언(다중 회귀)
from sklearn.linear_model import LinearRegression

model = LinearRegression()

# 모델 학습
model.fit(X_train_reduced, y_train)

# 모델 예측 - 회귀계수 유의성 검증 후에 해달 칼럼 제거하여 예측해야하는 것 몰랐음
X_test_reduced = df3_1_test.drop(["id", "f3", "f5","design"], axis=1)
y_test_pred = model.predict(X_test_reduced)

# 예측값과 실제값 피어슨 상관계수(소수점 셋째 자리 반올림) - 몰랐음
from scipy.stats import pearsonr
y_test_actual = df3_1_test["design"]
pearson_corr, _ = pearsonr(y_test_actual, y_test_pred)
pearson_corr = round(pearson_corr, 3)
print(pearson_corr)     # 결과: 0.944

0.944

In [239]:
# 모델 예측 점수 계산(RMSE)
from sklearn.metrics import mean_squared_error
rmse = mean_squared_error(y_test_actual, y_test_pred)
print("RMSE:", rmse)        # RMSE: 19.149971930635683

RMSE: 19.149971930635683

### 2. 한 통신 회사에서는 고객 이탈을 줄이고자 주요 원인들을 분석하기로 결정하였다. 이를 위해 500명의 고객 데이터를 수집했으며, 고객의 서비스 이용 및 가입 정보, 그리고 일부 개인적인 속성을 조사하였다.

1. 고객 이탈을 예측하는 로지스틱 회귀를 시행한 후 col1 칼럼의 p-value를 구하시오 (소수점 넷째 자리에서 반올림)
2. 폰 서비스를 받지 않은 고객 대비 받은 고객의 이탈 확률 오즈비를 구하시오 (소수점 넷째 자리에서 반올림)
3. 이탈할 확률이 0.3이상인 고객 수를 구하시오.

In [240]:
import pandas as pd

df3_2 = pd.read_csv("https://raw.githubusercontent.com/YoungjinBD/data/main/exam/9_3_2.csv")
df3_2.head()

        col1       col2  Phone_Service  Tech_Insurance  churn
0  54.967142  34.630888              0               1      0
1  48.617357  39.547083              0               0      0
2  56.476885  23.007162              1               0      1
3  65.230299  32.814846              1               0      1
4  47.658466  26.746787              0               1      1

In [241]:
df3_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   col1            500 non-null    float64
 1   col2            500 non-null    float64
 2   Phone_Service   500 non-null    int64
 3   Tech_Insurance  500 non-null    int64
 4   churn           500 non-null    int64
dtypes: float64(2), int64(3)
memory usage: 19.7 KB

In [242]:
df3_2["Phone_Service"].value_counts()

Phone_Service
1    307
0    193
Name: count, dtype: int64

In [243]:
df3_2["Tech_Insurance"].value_counts()

Tech_Insurance
1    348
0    152
Name: count, dtype: int64

In [244]:
df3_2["churn"].value_counts()

churn
1    251
0    249
Name: count, dtype: int64

In [ ]:
# 변수 분할
X_logistic = df3_2.drop("churn", axis=1)
y_logistic = df3_2["churn"]

# p-value 계산을 위한 statsmodels 사용(소수점 넷째 자리 반올림) - 몰랐음
import statsmodels.api as sm
X_logistic_sm = sm.add_constant(X_logistic)  # 상수항 추가
model_logistic_sm = sm.Logit(y_logistic, X_logistic_sm).fit()
print(model_logistic_sm.summary())

Optimization terminated successfully.
         Current function value: 0.640721
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:                  churn   No. Observations:                  500
Model:                          Logit   Df Residuals:                      495
Method:                           MLE   Df Model:                            4
Date:                Sun, 17 May 2026   Pseudo R-squ.:                 0.07562
Time:                        17:09:14   Log-Likelihood:                -320.36
converged:                       True   LL-Null:                       -346.57
Covariance Type:            nonrobust   LLR p-value:                 1.128e-10
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
const             -1.5390      0.824     -1.868      0.062      -3.154       0.076
col1               0.0545      0.010      5.292      0.000       0.034       0.075
col2              -0.0430      0.020     -2.197      0.028      -0.081      -0.005
Phone_Service      0.6244      0.194      3.210      0.001       0.243       1.006
Tech_Insurance    -0.3770      0.207     -1.824      0.068      -0.782       0.028
==================================================================================

In [246]:
# 로지스틱 회귀 모델 선언
from sklearn.linear_model import LogisticRegression
model_logistic = LogisticRegression(random_state=42)

model_logistic.fit(X_logistic, y_logistic)

LogisticRegression(random_state=42)

In [ ]:
# 이탈 확률 오즈비 계산 - 몰랐음
import numpy as np
odds_ratios = pd.Series(model_logistic.coef_[0], index=X_logistic.columns)
odds_ratios = odds_ratios.apply(lambda x: round(np.exp(x), 4))
print(odds_ratios)

col1              1.0560
col2              0.9580
Phone_Service     1.8242
Tech_Insurance    0.6972
dtype: float64

In [ ]:
# 이탈 확률이 0.3 이상인 고객 수 계산 - 몰랐음
y_pred_proba = model_logistic.predict_proba(X_logistic)[:, 1]
num_customers_high_risk = (y_pred_proba >= 0.3).sum()
print(num_customers_high_risk)  # 결과 449

449